// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  CriticMarkup = 1,
  Addition = 2,
  AdditionStart = 3,
  AdditionEnd = 4,
  Deletion = 5,
  DeletionStart = 6,
  DeletionEnd = 7,
  Substitution = 8,
  SubstitutionStart = 9,
  SubstitutionMiddle = 10,
  SubstitutionEnd = 11,
  Highlight = 12,
  HighlightStart = 13,
  HighlightEnd = 14,
  Comment = 15,
  CommentStart = 16,
  CommentEnd = 17
