# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Necessary for the provenance generation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Enable Corepack
        run: |
          corepack enable
      - name: Install dependencies
        run: |
          yarn install --immutable
      - name: Generate grammar
        run: yarn generate-grammar
      - name: Build package
        run: |
          yarn build
      - name: Test package
        run: |
          yarn test
      # Ensure we can take a look at what is included
      - name: Produce debug output (--dry-run)
        run: |
          npm pack --dry-run
      # NOTE: --provenance creates a verification that the package was built
      # here on GitHub Actions
      - name: Publish package
        run: |
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
